### ISSUE TITLE
Kodiranje znakov pri zemljevidu

### ISSUE THREAD

**Issue by jaanos** [tinkaracadez/APPR-2020-21#3]
Vidim, da pri uvozu zemljevida podajaš napačno kodiranje znakov, zaradi česar se šumniki ne uvozijo pravilno:
https://github.com/tinkaracadez/APPR-2020-21/blob/07cfdcfdc4655b4465794a251cecd558b5492436/vizualizacija/vizualizacija.r#L12-L13
Pri uvozu zemljevidov iz GADM uporabi kodiranje znakov **UTF-8**. Potem ne bo treba nadomeščati napačno uvoženih šumnikov (kar lahko na drugih sistemih povzroči probleme).

Mimogrede, opažam, da na začetku `vizualizacija.r` uvažaš knjižnice (prav tako tudi v `uvoz.r`), nato pa kličeš še `libraries.r` in `uvozi.zemljevid.r`. Tega ti ni treba početi - najbolje, da vse uvoze knjižnic narediš v `libraries.r` (tam se tudi že uvozi funkcija za delo z zemljevidi), pa vsakič pred začetkom dela poženeš ta program, da se uvozijo vse potrebne knjižnice (potem pa še uvoz, itd.).

**Comment by tinkaracadez** [comment]
Najlepša hvala, sem popravila.

**Comment by jaanos** [comment]
Še vedno v `vizualizacija.r` kličeš `uvozi.zemljevid.r` in `libraries.r` (slednjega sedaj tudi v `uvoz.r`). To kar odstrani, saj se programa uvozita na začetku prevajanja poročila. Pred začetkom dela tako kar ročno zaženi `libraries.r` (lahko zaženeš ustrezno vrstico v `projekt.Rmd`).

**Comment by tinkaracadez** [comment]
Aha, razumem. Bom odstranila. Kje v poročilu pa se potem kliče funkcija uvozi.zemljevid.r?

**Comment by tinkaracadez** [comment]
Sem ugotovila, da to funkcijo pokličemo v libraries.r in samo to potem v poročilu. Hvala za pomoč.
