### ISSUE TITLE
Težave z Binderjem

### ISSUE THREAD

**Issue by tinkaracadez** [tinkaracadez/APPR-2020-21#4]
Imam težave pri odpiranju dokumenta z Binderjem. RStudio se mi odpre, ko poskušam zagnati Shiny pa dolgo časa nalaga, nato pa mi javi error. Morda veste, v čem je težava?

**Comment by katarinabrilej** [comment]
Problem je v naslednji vrstici v datoteki `projekt.Rmd`
```
source("uvoz/uvoz.R", encoding="UTF-8"),
```
saj ima datoteka `uvoz.r `v resnici končnico `.r` in ne `.R`.

**Comment by tinkaracadez** [comment]
Hvala, sem popravila.
